### ISSUE TITLE
Basic To-Do's

### ISSUE THREAD

**Issue by sblapray1014** [sblapray1014/groupproject1#1]
- [ ] Add HTML outline
- [ ] Create standard file and folder structure
- [ ] Create overall UI layout 
- [ ] Add BootStrap CDN
- [ ] Add jQuery CDN
- [ ] Add basic JS script tag
- [ ] Research The Movie DB API
- [ ] Research IDGB API (Video Games)
